development:
  adapter: postgresql
  encoding: unicode
  database: databasename
  pool: 5
  username: postgres
  passwor:

test:
  adapter: postgresql
  encoding: unicode
  database: demo_test_test
  pool: 5
  username: postgres
  password:
  timeout: 5000


